"""
Shared MAMMAL prompt constants for examples and tests.

This module contains pre-formatted MAMMAL prompt strings that can be reused
across different examples and test files.
"""

# ---------------------------------------------------------------------------
# Pre-formatted MAMMAL prompt strings
# ---------------------------------------------------------------------------

PROTEIN_CALMODULIN = (
    "<@TOKENIZER-TYPE=AA>"
    "<MOLECULAR_ENTITY><MOLECULAR_ENTITY_OF_TYPE_PROTEIN>"
    "MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMISELDQDGFIDKEDLHDGDGKISFEEFLNLVNK"
    "EMTADVDGDGQVNYEEFVTMMTSK"
    "<EOS>"
)

PROTEIN_FLUORESCENT = (
    "<@TOKENIZER-TYPE=AA>"
    "<MOLECULAR_ENTITY><MOLECULAR_ENTITY_OF_TYPE_PROTEIN>"
    "MSKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGDATNGKLTLKFICTTGKLPVPWPTLVTTLSYGVQCFSRYPDHMKQHDFFKSAM"
    "PEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQ"
    "LADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"    
    "<EOS>"
)

SMILES_ASPIRIN = (
    "<@TOKENIZER-TYPE=SMILES>"
    "<MOLECULAR_ENTITY><MOLECULAR_ENTITY_OF_TYPE_SMALL_MOL>"
    "CC(=O)Oc1ccccc1C(=O)O"
    "<EOS>"
)

SMILES_CAFFEINE = (
    "<@TOKENIZER-TYPE=SMILES>"
    "<MOLECULAR_ENTITY><MOLECULAR_ENTITY_OF_TYPE_SMALL_MOL>"
    "Cn1cnc2c1c(=O)n(c(=O)n2C)C"
    "<EOS>"
)

SMILES_ETHER = (
    "<@TOKENIZER-TYPE=SMILES>"
    "<MOLECULAR_ENTITY><MOLECULAR_ENTITY_OF_TYPE_SMALL_MOL>"
    "COC(C)(C)C"
    "<EOS>"
)